name: HavenBags
main: valorless.havenbags.HavenBags
version: version-number
author: Valorless
api-version: 1.18
depend: [ValorlessUtils]
commands:
  havenbags:
    description: Main command.
    usage:
    aliases: bags
  havenbags reload:
    description: Reloads the configuration file.
    usage: /havenbags reload
    permission: havenbags.reload
    permission-message: You don't have havenbags.reload.
    aliases: bags reload
  havenbags create:
    description: Create bags.
    usage: /havenbags create
    permission-message: You don't have havenbags.create.
    aliases: bags create
  havenbags give:
    description: Give bags.
    usage: /havenbags give
    permission-message: You don't have havenbags.create.
    aliases: bags give
  havenbags restore:
    description: Restore bags.
    usage: /havenbags restore
    permission-message: You don't have havenbags.restore.
    aliases: bags restore
permissions:
  havenbags.*:
    description: Gives access to all HavenBags commands.
    children:
      havenbags.reload: true
      havenbags.use: true
      havenbags.create: true
      havenbags.restore: true
      havenbags.bypass: true
  havenbags.reload:
    description: Allows you to reload the configuration.
    default: op
  havenbags.use:
    description: Allows you to use bags.
    default: op
  havenbags.create:
    description: Allows you to create bags and give.
    default: op
  havenbags.restore:
    description: Allows you to restore bags.
    default: op
  havenbags.bypass:
    description: Allows you to bypass ownership locks.
    default: op
  