name: HavenBags
main: valorless.havenbags.Main
version: version-number
author: Valorless
api-version: 1.17
website: https://www.spigotmc.org/resources/110420/
description: Create shulker-like bags of varying sizes bound to a player, or accessible by anyone.
depend: [ValorlessUtils]
softdepend: [ChestSort, PlaceholderAPI]
commands:
  havenbags:
    description: Main command.
    usage:
    aliases: [bags, bag]
permissions:
  havenbags.*:
    description: Gives access to all HavenBags commands.
    children:
      havenbags.reload: true
      havenbags.use: true
#      havenbags.open: true
      havenbags.rename: true
      havenbags.create: true
      havenbags.give: true
      havenbags.restore: true
      havenbags.bypass: true
      havenbags.preview: true
      havenbags.info: true
      havenbags.gui: true
      havenbags.empty: true
      havenbags.help: true
      havenbags.autoloot: true
      havenbags.weight: true
  havenbags.reload:
    description: Allows you to reload the configuration.
    default: op
  havenbags.use:
    description: Allows you to use bags.
    default: op
#  havenbags.open:
#    description: Allows you to remotely open bags.
#    default: op
  havenbags.rename:
    description: Allows you to rename bags. Without havenbags.bypass, you can only rename your own bags.
    default: op
  havenbags.create:
    description: Allows you to create bags.
    default: op
  havenbags.give:
    description: Allows you to give bags.
    default: op
  havenbags.restore:
    description: Allows you to restore bags.
    default: op
  havenbags.bypass:
    description: Allows you to bypass ownership locks.
    default: op
  havenbags.preview:
    description: Allows you to bypass preview bags.
    default: op
  havenbags.info:
    description: Allows you to view information regarding the currently held-in-hand bag.
    default: op
  havenbags.gui:
    description: Allows you to open the Admin GUI.
    default: op
  havenbags.empty:
    description: Allows you to empty bags onto the ground.
    default: op
  havenbags.empty:
    description: Allows you to use '/havenbags help'.
    default: op
  havenbags.autopickup:
    description: Allows you to use the auto-pickup feature.
    default: op
  havenbags.weight:
    description: Allows you to set the weight limit of bags.
    default: op
  